# Project: Project1
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = stric.o acsii.o
LINKOBJ  = stric.o acsii.o
LIBS     = -L"C:/Users/BILAL/Desktop/Embarcadero/Dev-Cpp/TDM-GCC-64/lib" -L"C:/Users/BILAL/Desktop/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/BILAL/Desktop/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Users/BILAL/Desktop/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Users/BILAL/Desktop/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/Users/BILAL/Desktop/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Users/BILAL/Desktop/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Users/BILAL/Desktop/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Users/BILAL/Desktop/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = Project1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = C:\Users\BILAL\Desktop\Embarcadero\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

stric.o: stric.c
	$(CC) -c stric.c -o stric.o $(CFLAGS)

acsii.o: acsii.c
	$(CC) -c acsii.c -o acsii.o $(CFLAGS)
